import './SeatMap.css';

// Groups the flat seat list from GET /api/events/:id/seats into rows,
// mirroring the row-of-10 layout generated by the event-service.
function groupByRow(seats) {
  return seats.reduce((rows, seat) => {
    if (!rows[seat.row]) rows[seat.row] = [];
    rows[seat.row].push(seat);
    return rows;
  }, {});
}

export default function SeatMap({ seats, selected, onToggle }) {
  const rows = groupByRow(seats);
  const rowLabels = Object.keys(rows).sort();

  return (
    <div className="seatmap">
      <div className="seatmap-stage">Stage</div>

      {rowLabels.map((row) => (
        <div className="seatmap-row" key={row}>
          <span className="seatmap-row-label">{row}</span>
          <div className="seatmap-seats">
            {rows[row].map((seat) => {
              const isSelected = selected.includes(seat.seatNumber);
              const isTaken = seat.status !== 'available';
              return (
                <button
                  type="button"
                  key={seat.seatNumber}
                  disabled={isTaken}
                  className={[
                    'seat',
                    isTaken ? `seat-${seat.status}` : '',
                    isSelected ? 'seat-selected' : '',
                  ].join(' ')}
                  onClick={() => onToggle(seat.seatNumber)}
                  title={`Seat ${seat.seatNumber} — ${seat.status}`}
                >
                  {seat.seatNumber}
                </button>
              );
            })}
          </div>
        </div>
      ))}

      <div className="seatmap-legend">
        <span><i className="dot dot-available" /> Available</span>
        <span><i className="dot dot-selected" /> Selected</span>
        <span><i className="dot dot-locked" /> On hold</span>
        <span><i className="dot dot-booked" /> Booked</span>
      </div>
    </div>
  );
}
